myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'myapp/index', views.index, name='index'),
    path(r'myapp/about', views.about, name='about'),
    path(r'myapp/<int:topic_id>', views.detail, name='detail')
    ]

urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'myapp/index', views.index, name='index'),
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
    path(r'myapp/about', views.about, name='about'),
    path(r'myapp/<int:topic_id>', views.detail, name='detail')
]

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    length = models.IntegerField(blank=False, null=False, default=12)

    def __str__(self):
        return self.name


class Course(models.Model):
    title = models.CharField(max_length=200)
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Student(User):
    LVL_CHOICES = [
        ('HS', 'High School'),
        ('UG', 'Undergraduate'),
        ('PG', 'Postgraduate'),
        ('ND', 'No Degree'),
    ]

    level = models.CharField(choices=LVL_CHOICES, max_length=2, default='HS')
    address = models.CharField(max_length=300, blank=True, null=True)
    province = models.CharField(max_length=2, default='ON')
    registered_courses = models.ManyToManyField(Course, blank=True)
    interested_in = models.ManyToManyField(Topic)


class Order(models.Model):
    ODR_CHOICES = [
        (0, 'Cancelled'),
        (1, 'Confirmed'),
        (2, 'On Hold')
    ]
    courses = models.ManyToManyField(Course)
    student = models.ForeignKey(Student,  on_delete=models.CASCADE, null=True)
    order_status = models.IntegerField(choices=ODR_CHOICES, default=1)
    order_date = models.DateField(default=timezone.now)

    def total_cost(self):
        total_cost = 0
        for c in self.courses.all():
            total_cost = total_cost + c.price
        return total_cost

myapp/views.py
# Import necessary classes
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404

from .models import Topic, Course, Student, Order


# Create your views here.
def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index0.html', {'top_list': top_list})


def about(request):
    return render(request, 'myapp/about0.html')


def detail(request, topic_id):
    topic_name = get_object_or_404(Topic, id=topic_id).name
    topic_length = get_object_or_404(Topic, id=topic_id).length
    courses = Course.objects.filter(topic_id=topic_id)
    return render(request, 'myapp/detail0.html', {'topic_name': topic_name, 'topic_length': topic_length,
                                                  'courses': list(courses)})

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
    <p>This is an E-learning Website! Search our Topics to find all available Courses.</p>
    <p><a href="/myapp/index">Index page (hardcoded url)</a></p>
    <p><a href="{% url 'myapp:index' %}">Index page (url namespacing)</a></p>
</body>
</html>

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Name: {{ topic_name }}</p>
<p>Length: {{ topic_length }}</p>
{% if courses %}
    <h2>List of Course</h2>
    <ol>
        {% for course in courses  %}
            <li>{{ course }}</li>
        {% endfor %}
    </ol>
{% else %}
    <p>There is no available Course related to {{ topic_name }}</p>
{% endif %}
</body>
</html>

myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html lang="en">
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for top  in top_list %}
                <li> {{ top.name}} </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
    <p><a href="/myapp/about">About page (hardcoded url)</a></p>
    <p><a href='{% url 'myapp:about' %}'>About page (url namespacing)</a></p>
</body>
</html>